[build]
  command = "pip install -r requirements.txt"
  functions = "api"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/v1/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/api/v1/openapi.json"
  to = "/.netlify/functions/openapi"
  status = 200

[[redirects]]
  from = "/api/openapi"
  to = "/.netlify/functions/openapi"
  status = 200

[[redirects]]
  from = "/api/v1/auth/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/v1/jurisprudence/authority"
  to = "/.netlify/functions/authority"
  status = 200

[[redirects]]
  from = "/api/v1/precedents/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/v1/compare/systems"
  to = "/.netlify/functions/compare"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/docs"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"

# API endpoints security headers
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Documentation page security headers (more permissive for Swagger UI)
[[headers]]
  for = "/docs"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://unpkg.com; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https:; font-src 'self' https://unpkg.com"

# General security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"