name: JurisRank Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run basic tests
        run: |
          python -m pytest tests/test_basic.py -v
          
      - name: Validate OpenAPI schema
        run: |
          if [ -f "openapi_schema.json" ]; then
            python -c "import json; json.load(open('openapi_schema.json'))"
            echo "✅ OpenAPI schema is valid JSON"
          else
            echo "⚠️ OpenAPI schema not found"
          fi
          
      - name: Check documentation
        run: |
          echo "📚 Checking documentation files..."
          for file in README.md EXTERNAL_AUDIT_REPORT.md SECURITY_CHECKLIST.md; do
            if [ -f "$file" ]; then
              echo "✅ $file exists"
            else
              echo "❌ $file missing"
            fi
          done